In [1]:
import pandas as pd

# Load the dataset from a CSV file
dataset = pd.read_csv('C:/Users/thale/Desktop/Piyose/urbanandruralpopulation new.csv')

dataset

           country Code country  Year  Urban population Rural population
0      Afghanistan          AFG  1960            724373          7898093
1      Afghanistan          AFG  1961            763336          8026804
2      Afghanistan          AFG  1962            805062          8163985
3      Afghanistan          AFG  1963            849446          8308019
4      Afghanistan          AFG  1964            896820          8458694
...            ...          ...   ...               ...              ...
14163     Zimbabwe          ZWE  2017           4755312          9995789
14164     Zimbabwe          ZWE  2018           4848158         10204026
14165     Zimbabwe          ZWE  2019           4945719         10408889
14166     Zimbabwe          ZWE  2020           5052214         10617452
14167     Zimbabwe          ZWE  2021           5166388         10827136

[14168 rows x 5 columns]

# Informal Settlements Dataset Analysis

## Dataset Overview
The dataset selected was sourced from the **Humanitarian Data Exchange (HDX)**, a trusted platform managed by the United Nations. The dataset focuses on informal settlements and provides key information on settlement names, population sizes, geographic coordinates, and shelter types, among other variables.

## Justification for Dataset Selection
This dataset is suitable for the analysis of informal settlements because it contains several relevant columns:

- **Settlement_Name**: This column provides a unique identifier for each informal settlement, allowing us to study patterns and differentiate between various locations.
  
- **Population**: This column offers insight into the size of each settlement, which is essential for analyzing density, overcrowding, and resource needs.

Additionally, the data's source ensures its credibility, as it is published and regularly updated by the United Nations Office for the Coordination of Humanitarian Affairs (OCHA), a well-recognized organization in the field of humanitarian data.

## Data Completeness
The dataset is comprehensive, covering a wide range of settlements. By inspecting missing values, we can ensure the completeness and reliability of the dataset for our analysis.